CREATE DATABASE DDL
CREATE SCHEMA EMP_INFO

CREATE TABLE EMP_INFO.EMPLOYEE(
EMP_ID INT,
EMP_NAME VARCHAR,
EMP_SALARY DECIMAL
)

ALTER TABLE EMP_INFO.EMPLOYEE
ADD DEPARTMENT VARCHAR(50)

ALTER TABLE EMP_INFO.EMPLOYEE
DROP COLUMN EMP_SALARY

EXEC SP_RENAME 'EMP_INFO.EMPLOYEE.DEPARTMENT' , 'DeptName' , 'COLUMN'


CREATE SCHEMA PRO_INFO

CREATE TABLE PRO_INFO.PROJECT(
PROJECT_ID INT,
PROJECT_NAME VARCHAR
)

ALTER TABLE EMP_INFO.EMPLOYEE
ALTER COLUMN EMP_ID INT NOT NULL

ALTER TABLE EMP_INFO.EMPLOYEE
ADD PRIMARY KEY (EMP_ID)

ALTER TABLE EMP_INFO.EMPLOYEE
ADD UNIQUE (EMP_NAME)

CREATE SCHEMA CUST_INFO

CREATE TABLE CUST_INFO.CUSTOMERS(
CustomerID INT ,
FirstName VARCHAR,
LastName  VARCHAR,	
Email VARCHAR,
Status VARCHAR
)

ALTER TABLE CUST_INFO.CUSTOMERS
ADD UNIQUE (FIRSTNAME,LASTNAME)

ALTER TABLE CUST_INFO.CUSTOMERS
ADD DEFAULT'ACTIVE' FOR Status

CREATE SCHEMA OR_INFO

CREATE TABLE OR_INFO.ORDERS(
ORDERID INT,
CUSTOMERID INT,
ORDERDATE DATETIME,
TOTALAMOUNT DECIMAL
)

ALTER TABLE OR_INFO.ORDERS
ADD CHECK (TOTALAMOUNT>0)

CREATE SCHEMA SALES
ALTER SCHEMA SALES TRANSFER OBJECT :: OR_INFO.ORDERS

EXEC SP_RENAME 'SALES.ORDERS' , 'SALESORDERS'

